syntax = "proto3";

package collection;

import "google/api/annotations.proto";

option go_package = "github.com/rexgreenway/collection-app/internal/gen/collection";

// ------- REQUEST TYPES -------

message Empty {}

message IdMessage {
  string id = 1;
}

// ------- RESPONSE TYPES -------

// Basic Collection
message Collection {
  string id = 1;
  string name = 2;
}

// ------- SERVICES -------

service CollectionService {
  // // GET /collections
  // rpc ListCollections(Empty) returns (stream Collection) {
  //   option (google.api.http) = {get: "/v1/collections"};
  // }

  // GET /collections/<id>
  rpc GetCollection(IdMessage) returns (Collection) {
    option (google.api.http) = {get: "/v1/collections/{id}"};
  }
}
