syntax = "proto3";

package collection;

import "google/api/annotations.proto";
import "google/api/field_behavior.proto";

option go_package = "github.com/rexgreenway/collection-app/internal/gen/collection";

// ------- REQUEST TYPES -------

message Empty {}

message IdMessage {
  string id = 1;
  QueryParams params = 2;
}

// ANY PARAMS NOT SENT IN ROUTE PATH will be the query params
message RequestWithQueryParams {
  string id = 1 [(google.api.field_behavior) = REQUIRED];
  string name = 2;

  // Query Params
  int32 page = 11;
  int32 size = 12;
}

// Can also put generic params into their own message
message RequestWithQueryParamsV2 {
  string id = 1;
  string name = 2;

  QueryParams params = 11;
}

message QueryParams {
  int32 page = 1;
  int32 size = 2;
}

// USEFUL: https://learn.microsoft.com/en-us/aspnet/core/grpc/json-transcoding-binding?view=aspnetcore-9.0

// ------- RESPONSE TYPES -------

// Basic Collection
message Collection {
  string id = 1;
  string name = 2;
}

// ------- SERVICES -------

service CollectionService {
  // GET /collections
  // rpc ListCollections(Empty) returns (stream Collection) {
  //   option (google.api.http) = {get: "/v1/collections"};
  // }

  // GET /collections/<id>
  rpc GetCollection(IdMessage) returns (Collection) {
    option (google.api.http) = {get: "/v1/collections/{id}"};
  }
}
