syntax = "proto3";

package v1.collection;

import "google/api/annotations.proto";
import "google/api/field_behavior.proto";
import "google/protobuf/empty.proto";

option go_package = "github.com/rexgreenway/collection-app/internal/gen/v1/collection";

// ------- BASIC TYPES -------

message Collection {
  string id = 1 [(google.api.field_behavior) = OUTPUT_ONLY];
  string name = 2;
}

// ------- REQUEST TYPES -------

message Id {
  string id = 1 [(google.api.field_behavior) = IDENTIFIER];
}

message CreateCollectionRequest {
  Collection collection = 1 [(google.api.field_behavior) = REQUIRED];
}

message UpdateCollectionRequest {
  string id = 1 [(google.api.field_behavior) = IDENTIFIER];

  Collection collection = 2 [(google.api.field_behavior) = REQUIRED];
}

// ------- RESPONSE TYPES -------

message GetCollectionResponse {
  Collection data = 1;
}

message ListCollectionsResponse {
  repeated Collection data = 1 [(google.api.field_behavior) = UNORDERED_LIST];
}

// ------- SERVICES -------

service CollectionService {
  rpc ListCollections(google.protobuf.Empty) returns (ListCollectionsResponse) {
    option (google.api.http) = {get: "/collections"};
  }

  rpc CreateCollection(CreateCollectionRequest) returns (GetCollectionResponse) {
    option (google.api.http) = {
      post: "/collections"
      body: "collection"
    };
  }

  rpc GetCollection(Id) returns (GetCollectionResponse) {
    option (google.api.http) = {get: "/collections/{id}"};
  }

  rpc UpdateCollection(UpdateCollectionRequest) returns (GetCollectionResponse) {
    option (google.api.http) = {
      patch: "/collections/{id}"
      body: "collection"
    };
  }

  rpc DeleteCollection(Id) returns (google.protobuf.Empty) {
    option (google.api.http) = {delete: "/collections/{id}"};
  }
}
