syntax = "proto3";

package v1.collection;

import "google/api/annotations.proto";
import "google/protobuf/empty.proto";
import "v1/collection/requests.proto";
import "v1/collection/responses.proto";

option go_package = "github.com/rexgreenway/collection-app/internal/gen/v1/collection";

service CollectionService {
  // ------- Collections -------
  rpc ListCollections(ListCollectionsRequest) returns (ListCollectionsResponse) {
    option (google.api.http) = {get: "/collections"};
  }

  rpc CreateCollection(CreateCollectionRequest) returns (GetCollectionResponse) {
    option (google.api.http) = {
      post: "/collections"
      body: "collection"
    };
  }

  rpc GetCollection(CollectionId) returns (GetCollectionResponse) {
    option (google.api.http) = {get: "/collections/{id}"};
  }

  rpc UpdateCollection(UpdateCollectionRequest) returns (GetCollectionResponse) {
    option (google.api.http) = {
      patch: "/collections/{id}"
      body: "collection"
    };
  }

  rpc DeleteCollection(CollectionId) returns (google.protobuf.Empty) {
    option (google.api.http) = {delete: "/collections/{id}"};
  }

  // ------- Items -------
  rpc ListItems(ListItemsRequest) returns (ListItemsResponse) {
    option (google.api.http) = {get: "/collections/{collection_id}/items"};
  }

  rpc CreateItem(CreateItemRequest) returns (GetItemResponse) {
    option (google.api.http) = {
      post: "/collections/{collection_id}/items"
      body: "item"
    };
  }

  rpc CreateItems(CreateItemsRequest) returns (ListItemsResponse) {
    option (google.api.http) = {
      post: "/collections/{collection_id}/items:batchCreate"
      body: "items"
    };
  }

  rpc GetItem(CollectionItemId) returns (GetItemResponse) {
    option (google.api.http) = {get: "/collections/{collection_id}/items/{id}"};
  }

  rpc UpdateItem(UpdateItemRequest) returns (GetItemResponse) {
    option (google.api.http) = {
      patch: "/collections/{collection_id}/items/{id}"
      body: "item"
    };
  }

  rpc DeleteItem(CollectionItemId) returns (google.protobuf.Empty) {
    option (google.api.http) = {delete: "/collections/{collection_id}/items/{id}"};
  }
}
