// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/rexgreenway/collection-app/internal/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// CreateCollection provides a mock function for the type MockStore
func (_mock *MockStore) CreateCollection(collection entities.Collection) (entities.Collection, error) {
	ret := _mock.Called(collection)

	if len(ret) == 0 {
		panic("no return value specified for CreateCollection")
	}

	var r0 entities.Collection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(entities.Collection) (entities.Collection, error)); ok {
		return returnFunc(collection)
	}
	if returnFunc, ok := ret.Get(0).(func(entities.Collection) entities.Collection); ok {
		r0 = returnFunc(collection)
	} else {
		r0 = ret.Get(0).(entities.Collection)
	}
	if returnFunc, ok := ret.Get(1).(func(entities.Collection) error); ok {
		r1 = returnFunc(collection)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CreateCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCollection'
type MockStore_CreateCollection_Call struct {
	*mock.Call
}

// CreateCollection is a helper method to define mock.On call
//   - collection entities.Collection
func (_e *MockStore_Expecter) CreateCollection(collection any) *MockStore_CreateCollection_Call {
	return &MockStore_CreateCollection_Call{Call: _e.mock.On("CreateCollection", collection)}
}

func (_c *MockStore_CreateCollection_Call) Run(run func(collection entities.Collection)) *MockStore_CreateCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entities.Collection
		if args[0] != nil {
			arg0 = args[0].(entities.Collection)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_CreateCollection_Call) Return(collection1 entities.Collection, err error) *MockStore_CreateCollection_Call {
	_c.Call.Return(collection1, err)
	return _c
}

func (_c *MockStore_CreateCollection_Call) RunAndReturn(run func(collection entities.Collection) (entities.Collection, error)) *MockStore_CreateCollection_Call {
	_c.Call.Return(run)
	return _c
}

// CreateItem provides a mock function for the type MockStore
func (_mock *MockStore) CreateItem(item entities.Item) (entities.Item, error) {
	ret := _mock.Called(item)

	if len(ret) == 0 {
		panic("no return value specified for CreateItem")
	}

	var r0 entities.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(entities.Item) (entities.Item, error)); ok {
		return returnFunc(item)
	}
	if returnFunc, ok := ret.Get(0).(func(entities.Item) entities.Item); ok {
		r0 = returnFunc(item)
	} else {
		r0 = ret.Get(0).(entities.Item)
	}
	if returnFunc, ok := ret.Get(1).(func(entities.Item) error); ok {
		r1 = returnFunc(item)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CreateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateItem'
type MockStore_CreateItem_Call struct {
	*mock.Call
}

// CreateItem is a helper method to define mock.On call
//   - item entities.Item
func (_e *MockStore_Expecter) CreateItem(item any) *MockStore_CreateItem_Call {
	return &MockStore_CreateItem_Call{Call: _e.mock.On("CreateItem", item)}
}

func (_c *MockStore_CreateItem_Call) Run(run func(item entities.Item)) *MockStore_CreateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 entities.Item
		if args[0] != nil {
			arg0 = args[0].(entities.Item)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_CreateItem_Call) Return(item1 entities.Item, err error) *MockStore_CreateItem_Call {
	_c.Call.Return(item1, err)
	return _c
}

func (_c *MockStore_CreateItem_Call) RunAndReturn(run func(item entities.Item) (entities.Item, error)) *MockStore_CreateItem_Call {
	_c.Call.Return(run)
	return _c
}

// CreateItemBatch provides a mock function for the type MockStore
func (_mock *MockStore) CreateItemBatch(items []entities.Item) ([]entities.Item, error) {
	ret := _mock.Called(items)

	if len(ret) == 0 {
		panic("no return value specified for CreateItemBatch")
	}

	var r0 []entities.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]entities.Item) ([]entities.Item, error)); ok {
		return returnFunc(items)
	}
	if returnFunc, ok := ret.Get(0).(func([]entities.Item) []entities.Item); ok {
		r0 = returnFunc(items)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]entities.Item) error); ok {
		r1 = returnFunc(items)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CreateItemBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateItemBatch'
type MockStore_CreateItemBatch_Call struct {
	*mock.Call
}

// CreateItemBatch is a helper method to define mock.On call
//   - items []entities.Item
func (_e *MockStore_Expecter) CreateItemBatch(items any) *MockStore_CreateItemBatch_Call {
	return &MockStore_CreateItemBatch_Call{Call: _e.mock.On("CreateItemBatch", items)}
}

func (_c *MockStore_CreateItemBatch_Call) Run(run func(items []entities.Item)) *MockStore_CreateItemBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []entities.Item
		if args[0] != nil {
			arg0 = args[0].([]entities.Item)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_CreateItemBatch_Call) Return(items1 []entities.Item, err error) *MockStore_CreateItemBatch_Call {
	_c.Call.Return(items1, err)
	return _c
}

func (_c *MockStore_CreateItemBatch_Call) RunAndReturn(run func(items []entities.Item) ([]entities.Item, error)) *MockStore_CreateItemBatch_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCollection provides a mock function for the type MockStore
func (_mock *MockStore) DeleteCollection(collectionId string) error {
	ret := _mock.Called(collectionId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCollection")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(collectionId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_DeleteCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCollection'
type MockStore_DeleteCollection_Call struct {
	*mock.Call
}

// DeleteCollection is a helper method to define mock.On call
//   - collectionId string
func (_e *MockStore_Expecter) DeleteCollection(collectionId any) *MockStore_DeleteCollection_Call {
	return &MockStore_DeleteCollection_Call{Call: _e.mock.On("DeleteCollection", collectionId)}
}

func (_c *MockStore_DeleteCollection_Call) Run(run func(collectionId string)) *MockStore_DeleteCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_DeleteCollection_Call) Return(err error) *MockStore_DeleteCollection_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_DeleteCollection_Call) RunAndReturn(run func(collectionId string) error) *MockStore_DeleteCollection_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteItem provides a mock function for the type MockStore
func (_mock *MockStore) DeleteItem(itemId string) error {
	ret := _mock.Called(itemId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteItem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(itemId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_DeleteItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteItem'
type MockStore_DeleteItem_Call struct {
	*mock.Call
}

// DeleteItem is a helper method to define mock.On call
//   - itemId string
func (_e *MockStore_Expecter) DeleteItem(itemId any) *MockStore_DeleteItem_Call {
	return &MockStore_DeleteItem_Call{Call: _e.mock.On("DeleteItem", itemId)}
}

func (_c *MockStore_DeleteItem_Call) Run(run func(itemId string)) *MockStore_DeleteItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_DeleteItem_Call) Return(err error) *MockStore_DeleteItem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_DeleteItem_Call) RunAndReturn(run func(itemId string) error) *MockStore_DeleteItem_Call {
	_c.Call.Return(run)
	return _c
}

// GetCollection provides a mock function for the type MockStore
func (_mock *MockStore) GetCollection(collectionId string) (entities.Collection, error) {
	ret := _mock.Called(collectionId)

	if len(ret) == 0 {
		panic("no return value specified for GetCollection")
	}

	var r0 entities.Collection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (entities.Collection, error)); ok {
		return returnFunc(collectionId)
	}
	if returnFunc, ok := ret.Get(0).(func(string) entities.Collection); ok {
		r0 = returnFunc(collectionId)
	} else {
		r0 = ret.Get(0).(entities.Collection)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(collectionId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCollection'
type MockStore_GetCollection_Call struct {
	*mock.Call
}

// GetCollection is a helper method to define mock.On call
//   - collectionId string
func (_e *MockStore_Expecter) GetCollection(collectionId any) *MockStore_GetCollection_Call {
	return &MockStore_GetCollection_Call{Call: _e.mock.On("GetCollection", collectionId)}
}

func (_c *MockStore_GetCollection_Call) Run(run func(collectionId string)) *MockStore_GetCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_GetCollection_Call) Return(collection entities.Collection, err error) *MockStore_GetCollection_Call {
	_c.Call.Return(collection, err)
	return _c
}

func (_c *MockStore_GetCollection_Call) RunAndReturn(run func(collectionId string) (entities.Collection, error)) *MockStore_GetCollection_Call {
	_c.Call.Return(run)
	return _c
}

// GetItem provides a mock function for the type MockStore
func (_mock *MockStore) GetItem(itemId string) (entities.Item, error) {
	ret := _mock.Called(itemId)

	if len(ret) == 0 {
		panic("no return value specified for GetItem")
	}

	var r0 entities.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (entities.Item, error)); ok {
		return returnFunc(itemId)
	}
	if returnFunc, ok := ret.Get(0).(func(string) entities.Item); ok {
		r0 = returnFunc(itemId)
	} else {
		r0 = ret.Get(0).(entities.Item)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(itemId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItem'
type MockStore_GetItem_Call struct {
	*mock.Call
}

// GetItem is a helper method to define mock.On call
//   - itemId string
func (_e *MockStore_Expecter) GetItem(itemId any) *MockStore_GetItem_Call {
	return &MockStore_GetItem_Call{Call: _e.mock.On("GetItem", itemId)}
}

func (_c *MockStore_GetItem_Call) Run(run func(itemId string)) *MockStore_GetItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_GetItem_Call) Return(item entities.Item, err error) *MockStore_GetItem_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockStore_GetItem_Call) RunAndReturn(run func(itemId string) (entities.Item, error)) *MockStore_GetItem_Call {
	_c.Call.Return(run)
	return _c
}

// GetItemCountByCollectionId provides a mock function for the type MockStore
func (_mock *MockStore) GetItemCountByCollectionId(collectionId string) int32 {
	ret := _mock.Called(collectionId)

	if len(ret) == 0 {
		panic("no return value specified for GetItemCountByCollectionId")
	}

	var r0 int32
	if returnFunc, ok := ret.Get(0).(func(string) int32); ok {
		r0 = returnFunc(collectionId)
	} else {
		r0 = ret.Get(0).(int32)
	}
	return r0
}

// MockStore_GetItemCountByCollectionId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItemCountByCollectionId'
type MockStore_GetItemCountByCollectionId_Call struct {
	*mock.Call
}

// GetItemCountByCollectionId is a helper method to define mock.On call
//   - collectionId string
func (_e *MockStore_Expecter) GetItemCountByCollectionId(collectionId any) *MockStore_GetItemCountByCollectionId_Call {
	return &MockStore_GetItemCountByCollectionId_Call{Call: _e.mock.On("GetItemCountByCollectionId", collectionId)}
}

func (_c *MockStore_GetItemCountByCollectionId_Call) Run(run func(collectionId string)) *MockStore_GetItemCountByCollectionId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_GetItemCountByCollectionId_Call) Return(n int32) *MockStore_GetItemCountByCollectionId_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockStore_GetItemCountByCollectionId_Call) RunAndReturn(run func(collectionId string) int32) *MockStore_GetItemCountByCollectionId_Call {
	_c.Call.Return(run)
	return _c
}

// ListCollections provides a mock function for the type MockStore
func (_mock *MockStore) ListCollections(pagination *entities.Pagination) ([]entities.Collection, error) {
	ret := _mock.Called(pagination)

	if len(ret) == 0 {
		panic("no return value specified for ListCollections")
	}

	var r0 []entities.Collection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*entities.Pagination) ([]entities.Collection, error)); ok {
		return returnFunc(pagination)
	}
	if returnFunc, ok := ret.Get(0).(func(*entities.Pagination) []entities.Collection); ok {
		r0 = returnFunc(pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Collection)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*entities.Pagination) error); ok {
		r1 = returnFunc(pagination)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ListCollections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCollections'
type MockStore_ListCollections_Call struct {
	*mock.Call
}

// ListCollections is a helper method to define mock.On call
//   - pagination *entities.Pagination
func (_e *MockStore_Expecter) ListCollections(pagination any) *MockStore_ListCollections_Call {
	return &MockStore_ListCollections_Call{Call: _e.mock.On("ListCollections", pagination)}
}

func (_c *MockStore_ListCollections_Call) Run(run func(pagination *entities.Pagination)) *MockStore_ListCollections_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entities.Pagination
		if args[0] != nil {
			arg0 = args[0].(*entities.Pagination)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStore_ListCollections_Call) Return(collections []entities.Collection, err error) *MockStore_ListCollections_Call {
	_c.Call.Return(collections, err)
	return _c
}

func (_c *MockStore_ListCollections_Call) RunAndReturn(run func(pagination *entities.Pagination) ([]entities.Collection, error)) *MockStore_ListCollections_Call {
	_c.Call.Return(run)
	return _c
}

// ListItemsByCollectionId provides a mock function for the type MockStore
func (_mock *MockStore) ListItemsByCollectionId(collectionId string, pagination *entities.Pagination) ([]entities.Item, error) {
	ret := _mock.Called(collectionId, pagination)

	if len(ret) == 0 {
		panic("no return value specified for ListItemsByCollectionId")
	}

	var r0 []entities.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *entities.Pagination) ([]entities.Item, error)); ok {
		return returnFunc(collectionId, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *entities.Pagination) []entities.Item); ok {
		r0 = returnFunc(collectionId, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *entities.Pagination) error); ok {
		r1 = returnFunc(collectionId, pagination)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_ListItemsByCollectionId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListItemsByCollectionId'
type MockStore_ListItemsByCollectionId_Call struct {
	*mock.Call
}

// ListItemsByCollectionId is a helper method to define mock.On call
//   - collectionId string
//   - pagination *entities.Pagination
func (_e *MockStore_Expecter) ListItemsByCollectionId(collectionId any, pagination any) *MockStore_ListItemsByCollectionId_Call {
	return &MockStore_ListItemsByCollectionId_Call{Call: _e.mock.On("ListItemsByCollectionId", collectionId, pagination)}
}

func (_c *MockStore_ListItemsByCollectionId_Call) Run(run func(collectionId string, pagination *entities.Pagination)) *MockStore_ListItemsByCollectionId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *entities.Pagination
		if args[1] != nil {
			arg1 = args[1].(*entities.Pagination)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_ListItemsByCollectionId_Call) Return(items []entities.Item, err error) *MockStore_ListItemsByCollectionId_Call {
	_c.Call.Return(items, err)
	return _c
}

func (_c *MockStore_ListItemsByCollectionId_Call) RunAndReturn(run func(collectionId string, pagination *entities.Pagination) ([]entities.Item, error)) *MockStore_ListItemsByCollectionId_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCollection provides a mock function for the type MockStore
func (_mock *MockStore) UpdateCollection(id string, update entities.CollectionUpdate) (entities.Collection, error) {
	ret := _mock.Called(id, update)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCollection")
	}

	var r0 entities.Collection
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, entities.CollectionUpdate) (entities.Collection, error)); ok {
		return returnFunc(id, update)
	}
	if returnFunc, ok := ret.Get(0).(func(string, entities.CollectionUpdate) entities.Collection); ok {
		r0 = returnFunc(id, update)
	} else {
		r0 = ret.Get(0).(entities.Collection)
	}
	if returnFunc, ok := ret.Get(1).(func(string, entities.CollectionUpdate) error); ok {
		r1 = returnFunc(id, update)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_UpdateCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCollection'
type MockStore_UpdateCollection_Call struct {
	*mock.Call
}

// UpdateCollection is a helper method to define mock.On call
//   - id string
//   - update entities.CollectionUpdate
func (_e *MockStore_Expecter) UpdateCollection(id any, update any) *MockStore_UpdateCollection_Call {
	return &MockStore_UpdateCollection_Call{Call: _e.mock.On("UpdateCollection", id, update)}
}

func (_c *MockStore_UpdateCollection_Call) Run(run func(id string, update entities.CollectionUpdate)) *MockStore_UpdateCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 entities.CollectionUpdate
		if args[1] != nil {
			arg1 = args[1].(entities.CollectionUpdate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_UpdateCollection_Call) Return(collection entities.Collection, err error) *MockStore_UpdateCollection_Call {
	_c.Call.Return(collection, err)
	return _c
}

func (_c *MockStore_UpdateCollection_Call) RunAndReturn(run func(id string, update entities.CollectionUpdate) (entities.Collection, error)) *MockStore_UpdateCollection_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateItem provides a mock function for the type MockStore
func (_mock *MockStore) UpdateItem(id string, update entities.ItemUpdate) (entities.Item, error) {
	ret := _mock.Called(id, update)

	if len(ret) == 0 {
		panic("no return value specified for UpdateItem")
	}

	var r0 entities.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, entities.ItemUpdate) (entities.Item, error)); ok {
		return returnFunc(id, update)
	}
	if returnFunc, ok := ret.Get(0).(func(string, entities.ItemUpdate) entities.Item); ok {
		r0 = returnFunc(id, update)
	} else {
		r0 = ret.Get(0).(entities.Item)
	}
	if returnFunc, ok := ret.Get(1).(func(string, entities.ItemUpdate) error); ok {
		r1 = returnFunc(id, update)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_UpdateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateItem'
type MockStore_UpdateItem_Call struct {
	*mock.Call
}

// UpdateItem is a helper method to define mock.On call
//   - id string
//   - update entities.ItemUpdate
func (_e *MockStore_Expecter) UpdateItem(id any, update any) *MockStore_UpdateItem_Call {
	return &MockStore_UpdateItem_Call{Call: _e.mock.On("UpdateItem", id, update)}
}

func (_c *MockStore_UpdateItem_Call) Run(run func(id string, update entities.ItemUpdate)) *MockStore_UpdateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 entities.ItemUpdate
		if args[1] != nil {
			arg1 = args[1].(entities.ItemUpdate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_UpdateItem_Call) Return(item entities.Item, err error) *MockStore_UpdateItem_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockStore_UpdateItem_Call) RunAndReturn(run func(id string, update entities.ItemUpdate) (entities.Item, error)) *MockStore_UpdateItem_Call {
	_c.Call.Return(run)
	return _c
}
